/**
 * Times star-allele calling against a realistically sized array export.
 *
 * A 23andMe file is ~640,000 rows and 25 MB. This runs in the browser on the
 * user's machine during a live demo, so it needs to be comfortably sub-second,
 * not merely "eventually finishes".
 *
 * Run: npx tsx scripts/bench-genotype.ts
 */

import { callStarAlleles, looksLikeRawDna } from "../src/lib/genotype/call";

const MARKERS: Record<string, string> = {
  rs4244285: "AA",
  rs4986893: "GG",
  rs12248560: "CC",
  rs3892097: "TT",
  rs4149056: "CC",
  rs1799853: "CC",
  rs1057910: "AC",
  rs116855232: "GG",
  rs3918290: "CC",
};

function buildLargeExport(rowCount: number): string {
  const parts: string[] = [
    "# This data file generated by 23andMe at: Wed Apr 15 09:12:44 2026",
    "# rsid\tchromosome\tposition\tgenotype",
  ];
  for (const [rsid, gt] of Object.entries(MARKERS)) {
    parts.push(`${rsid}\t10\t96541616\t${gt}`);
  }
  const bases = ["AA", "AG", "GG", "CT", "TT", "CC", "--"];
  for (let i = 0; i < rowCount; i++) {
    parts.push(`rs${1000000 + i}\t${(i % 22) + 1}\t${10000 + i}\t${bases[i % 7]}`);
  }
  return parts.join("\n");
}

const ROWS = 640_000;
console.log(`Building a ${ROWS.toLocaleString()}-row export…`);
const t0 = Date.now();
const text = buildLargeExport(ROWS);
console.log(
  `  built ${(text.length / 1024 / 1024).toFixed(1)} MB in ${Date.now() - t0} ms\n`,
);

const t1 = Date.now();
const detected = looksLikeRawDna(text);
const detectMs = Date.now() - t1;

const t2 = Date.now();
const result = callStarAlleles(text);
const callMs = Date.now() - t2;

console.log(`Detection : ${detectMs} ms (raw DNA: ${detected})`);
console.log(`Parse+call: ${callMs} ms`);
console.log(`  scanned ${result.totalRows.toLocaleString()} rows, kept ${result.matchedRows} markers`);
console.log(
  `  calls: ${result.calls
    .filter((c) => c.status === "called")
    .map((c) => `${c.gene} ${c.diplotype}`)
    .join(", ")}`,
);

const budgetMs = 2000;
const ok = callMs < budgetMs && detectMs < 50;
console.log(
  `\n${ok ? "PASS" : "FAIL"} — parse+call ${callMs} ms against a ${budgetMs} ms budget, detection ${detectMs} ms`,
);
process.exit(ok ? 0 : 1);
