/**
 * Validates star-allele calling from synthetic raw array files.
 *
 * The load-bearing check is the last one: every diplotype the caller emits has
 * to resolve against a real CPIC lookup row. A string like "*1/*2" that CPIC
 * happens to write differently would produce no findings and no error — the
 * product would look like it worked and quietly tell the user nothing.
 *
 * Run: npx tsx scripts/verify-genotype-calling.ts
 */

import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { callStarAlleles, looksLikeRawDna, parseRawDna } from "../src/lib/genotype/call";
import { resolveGenotype, analyse } from "../src/lib/cpic/match";

let failures = 0;
function check(label: string, ok: boolean, detail = "") {
  if (!ok) failures++;
  console.log(`  [${ok ? "PASS" : "FAIL"}] ${label}${detail ? ` — ${detail}` : ""}`);
}

/** Builds a 23andMe-format file from a set of genotypes, plus filler rows. */
function buildFile(genotypes: Record<string, string>, filler = 200): string {
  const header = [
    "# This data file generated by 23andMe at: Wed Apr 15 09:12:44 2026",
    "# This file contains raw genotype data, including data that is not used in 23andMe reports.",
    "# rsid\tchromosome\tposition\tgenotype",
  ];
  const rows = Object.entries(genotypes).map(
    ([rsid, gt], i) => `${rsid}\t${(i % 22) + 1}\t${1000000 + i * 137}\t${gt}`,
  );
  for (let i = 0; i < filler; i++) {
    rows.push(`rs${9000000 + i}\t${(i % 22) + 1}\t${500000 + i * 91}\tAG`);
  }
  return [...header, ...rows].join("\n");
}

/* ------------------------------------------------------------------ */
console.log("=== 1. Format detection and parsing ===");

const demo = buildFile({
  rs4244285: "AA", // CYP2C19 *2/*2
  rs4986893: "GG", // CYP2C19 *3 absent
  rs12248560: "CC", // CYP2C19 *17 absent
  rs3892097: "TT", // CYP2D6 *4/*4
  rs4149056: "CC", // SLCO1B1 *5/*5
  rs1799853: "CC", // CYP2C9 *2 absent
  rs1057910: "AC", // CYP2C9 *3 het
  rs116855232: "GG", // NUDT15 reference
  rs3918290: "CC", // DPYD reference
});

check("detects a raw array file", looksLikeRawDna(demo));
check(
  "does not mistake a lab report for raw data",
  !looksLikeRawDna("Gene Result\nCYP2C19 *2/*2\nPatient: A Morgan"),
);

const parsed = parseRawDna(demo);
check("identifies 23andMe layout", parsed.format === "23andme", parsed.format);
check("picks out only the marker SNPs", parsed.snps.size === 9, `${parsed.snps.size} of 209 rows`);

/* ------------------------------------------------------------------ */
console.log("\n=== 2. Diplotype calls ===");

const result = callStarAlleles(demo);
const byGene = new Map(result.calls.map((c) => [c.gene, c]));
for (const c of result.calls) {
  const status = c.status === "called" ? c.diplotype : `uncallable (${c.reason})`;
  console.log(`  ${c.gene.padEnd(9)} ${String(status).padEnd(28)} markers ${c.covered}/${c.required}`);
}

check("CYP2C19 -> *2/*2", byGene.get("CYP2C19")?.diplotype === "*2/*2");
check("CYP2D6 -> *4/*4", byGene.get("CYP2D6")?.diplotype === "*4/*4");
check("SLCO1B1 -> *5/*5", byGene.get("SLCO1B1")?.diplotype === "*5/*5");
check("CYP2C9 het -> *1/*3", byGene.get("CYP2C9")?.diplotype === "*1/*3");
check("NUDT15 reference -> *1/*1", byGene.get("NUDT15")?.diplotype === "*1/*1");
check(
  "DPYD reference uses CPIC's 'Reference', not *1",
  byGene.get("DPYD")?.diplotype === "Reference/Reference",
  byGene.get("DPYD")?.diplotype ?? "null",
);

/* ------------------------------------------------------------------ */
console.log("\n=== 3. Refusals: the cases that must NOT produce a call ===");

// rs4244285 is defined G>A. Seeing C/T means the definition is on the wrong
// strand — the guard must catch it rather than emit a confident wrong call.
const wrongStrand = callStarAlleles(buildFile({ rs4244285: "CT" }));
const cyp2c19Bad = wrongStrand.calls.find((c) => c.gene === "CYP2C19");
check(
  "off-definition bases refuse the gene (strand guard)",
  cyp2c19Bad?.status === "uncallable",
  cyp2c19Bad?.reason ?? "",
);

const noCall = callStarAlleles(buildFile({ rs4149056: "--" }));
const slco = noCall.calls.find((c) => c.gene === "SLCO1B1");
check(
  "a '--' no-call is treated as missing, not as data",
  slco?.status === "uncallable" && slco.covered === 0,
);

const dup = callStarAlleles(buildFile({ rs4244285: "AA", rs12248560: "TT" }));
const cyp2c19Dup = dup.calls.find((c) => c.gene === "CYP2C19");
check(
  "more than two variant copies refuses rather than guesses",
  cyp2c19Dup?.status === "uncallable",
  cyp2c19Dup?.reason ?? "",
);

const partial = callStarAlleles(buildFile({ rs4244285: "GG" })); // *2 only, *3/*17 absent
const cyp2c19Partial = partial.calls.find((c) => c.gene === "CYP2C19");
check(
  "a reference call on incomplete markers is flagged partial",
  cyp2c19Partial?.status === "called" && cyp2c19Partial.partial === true,
  `covered ${cyp2c19Partial?.covered}/${cyp2c19Partial?.required}`,
);

/* ------------------------------------------------------------------ */
console.log("\n=== 4. Every emitted diplotype resolves against CPIC ===");

for (const call of result.calls) {
  if (call.status !== "called" || !call.diplotype) continue;
  const resolved = resolveGenotype({ gene: call.gene, diplotype: call.diplotype });
  check(
    `${call.gene} ${call.diplotype}`,
    resolved !== null,
    resolved ? resolved.phenotype : "NO CPIC ROW — would silently yield nothing",
  );
}

/* ------------------------------------------------------------------ */
console.log("\n=== 5. Full path: raw file -> findings ===");

const genotypes = result.calls
  .filter((c) => c.status === "called" && c.diplotype)
  .map((c) => ({ gene: c.gene, diplotype: c.diplotype! }));

const analysis = analyse({
  genotypes,
  medications: ["Plavix 75mg", "simvastatin 40mg", "codeine 30mg", "ibuprofen 400mg"],
});

console.log(`  ${analysis.summary.high} high, ${analysis.summary.caution} caution`);
for (const f of analysis.findings) {
  console.log(`   [${f.severity.toUpperCase()}] ${f.drugName}: ${f.recommendation.slice(0, 76)}`);
}
check("raw file produces high-severity findings", analysis.summary.high > 0);
check(
  "clopidogrel flagged from an array-derived genotype",
  analysis.findings.some((f) => f.drugName === "clopidogrel" && f.severity === "high"),
);

/* ------------------------------------------------------------------ */
console.log("\n=== 6. The committed sample file (what the demo actually uploads) ===");

const samplePath = join(process.cwd(), "public", "sample-23andme.txt");
if (!existsSync(samplePath)) {
  check("public/sample-23andme.txt exists", false, "run: node scripts/make-sample-dna.mjs");
} else {
  const sampleText = readFileSync(samplePath, "utf8");
  const sample = callStarAlleles(sampleText);
  console.log(
    `  ${sample.totalRows.toLocaleString()} rows, ${sample.matchedRows} markers matched`,
  );
  for (const c of sample.calls) {
    console.log(
      `  ${c.gene.padEnd(9)} ${String(c.status === "called" ? c.diplotype : "not called").padEnd(24)} ${c.covered}/${c.required}`,
    );
  }

  const s = new Map(sample.calls.map((c) => [c.gene, c]));
  check("sample is detected as raw DNA", looksLikeRawDna(sampleText));
  check("sample -> CYP2C19 *2/*2", s.get("CYP2C19")?.diplotype === "*2/*2");
  check("sample -> CYP2D6 *4/*4", s.get("CYP2D6")?.diplotype === "*4/*4");
  check("sample -> SLCO1B1 *5/*5", s.get("SLCO1B1")?.diplotype === "*5/*5");
  check(
    "sample -> CYP2C9 *1/*3 (the marker that collided with filler)",
    s.get("CYP2C9")?.diplotype === "*1/*3",
    s.get("CYP2C9")?.diplotype ?? "null",
  );
  check(
    "every sample gene is callable",
    sample.calls.every((c) => c.status === "called"),
  );

  const sampleAnalysis = analyse({
    genotypes: sample.calls
      .filter((c) => c.status === "called" && c.diplotype)
      .map((c) => ({ gene: c.gene, diplotype: c.diplotype! })),
    medications: ["Plavix 75mg", "simvastatin 40mg", "codeine 30mg"],
  });
  check(
    "sample file yields 3 high-severity findings for the demo drugs",
    sampleAnalysis.summary.high === 3,
    `got ${sampleAnalysis.summary.high}`,
  );
}

console.log(failures === 0 ? "\nAll checks passed.\n" : `\n${failures} check(s) FAILED.\n`);
process.exit(failures === 0 ? 0 : 1);
